<?php
/**
 * Replace the form key with the form key place holder
 */
?>
<?php
$moduleEnabled = Mage::getStoreConfigFlag(Phoenix_VarnishCache_Model_Observer::CONFIG_ENABLED);
$formKeyEnabled = Mage::getStoreConfigFlag(Phoenix_VarnishCache_Model_Observer::CONFIG_ENABLED_FORM_KEY);
$formKey = ($moduleEnabled && $formKeyEnabled) ? Phoenix_VarnishCache_Model_Observer::FORM_KEY_PLACEHOLDER : Mage::getSingleton('core/session')->getFormKey();
?>
<input name="form_key" type="hidden" value="<?php echo $formKey ?>" />
